basket/urls.py
from django.urls import path
from . import views 

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls', namespace='tienda')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.productos_all, name='productos_all'),
    path('libro/<slug:slug>/', views.producto_detail, name='producto_detail'),
    path('search/<slug:categoria_slug>/', views.category_list, name='category_list'),
    path('acerca', views.acerca, name='acerca'),
    





    
]

tienda/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(activo=True)


class Categoria(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)


    class meta:
        verbose_name_plural = 'Categorias'

    def get_absolute_url(self):
        return reverse('tienda:category_list', args=[self.slug])


    def __str__(self):
        return self.name



class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='producto', on_delete=models.CASCADE)
    creado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='creador_producto' )
    titulo = models.CharField(max_length=255)
    autor = models.CharField(max_length=255, default='admin')
    descripcion = models.TextField(blank=True)
    imagen = models.ImageField(upload_to='images/', default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    stock = models.BooleanField(default=True)
    precio = models.DecimalField(max_digits=4, decimal_places=2)
    activo = models.BooleanField(default=True)
    creado = models.DateField(auto_now_add=True)
    actualizado = models.DateField(auto_now=True)
    productos = ProductManager()
    objects = models.Manager()

    

    

    class Meta:
        verbose_name_plural = 'Productos'
        ordering = ('-creado',)

    def get_absolute_url(self):
        return reverse('tienda:producto_detail', args=[self.slug] )
        


    def __str__(self):
        return self.titulo


        

tienda/views.py
from .models import Categoria, Producto
from django.shortcuts import get_object_or_404, render
# Create your views here.


def productos_all(request):
    productos= Producto.objects.filter(activo=True)
    return render(request, 'tienda/home.html', {'productos': productos})


def producto_detail(request, slug):
    producto = get_object_or_404(Producto, slug=slug, stock=True)
    return render(request, 'tienda/productos/single.html', {'producto' : producto})

def category_list(request, categoria_slug=None):
    categoria = get_object_or_404(Categoria, slug=categoria_slug)
    productos = Producto.objects.filter(categoria=categoria)
    return render(request, 'tienda/productos/categoria.html', {'categoria': categoria, 'productos': productos})

def acerca(request):
    return render(request, 'tienda/acerca.html')

templates/tienda/productos/categoria.html
{% extends "../base.html" %}
{% load static %}

{% block title %}
{% if categoria %}{{ categoria.name }}{% else %} Productos{% endif %}
{% endblock %}

{%block content%}
<main>
  
 <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">Nuestros libros</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for productos in productos %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Imagen Responsiva" src="{{ productos.imagen.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ productos.get_absolute_url }}">{{ productos.titulo }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Articulo Nuevo</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/tienda/productos/single.html
{% extends "tienda/base.html" %}
{% load static %}
{% block title %}
{{ producto.name }}
{% endblock %}
{% block content %}


<main class="pt-2">

    <div class="container" style="max-width: 1000px">

        <div class="row g-3">
            <div class="alert alert-light fw600 rounded-0 border-0 py-3" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                    class="bi bi-info-circle me-2" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                    <path
                        d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                </svg>
                Todos nuestros productos cuentan con garantia y devolucion.
            </div>
            <div class="col-12 d-flex justify-content-between">

            </div>

            <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
                <div class="d-grid gap-2">

                                  <p><span class="lead">{{ producto.autor }}</span> (Autor)</p>

                        </div>

                        <div class="">                        <div><p>{{ producto.descripcion|slice:":355" }}...</p></div>

  <div class="d-flex d-flex-inline justify-content-between">
                        <div><span class="h3">${{ producto.precio }}</span>
                            <p class="text-muted">Incluye iva</p>

                            <label for="select">Cantidad</label>
                            <select id="select" class="h6" style="width:50px;height:40px;">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                    </div>
                    <hr>
                    <button type="button" id="add-button" value="{{producto.id}}" class="btn btn-success fw500">Añadir
                        al carrito</button>
                    <button type="button" id="favoritos" value="" class="btn btn-success fw500">Añadir a
                        favoritos</button>

                </div>
            </div>

            <div class="col-md-7 col-lg-7 p-0">



                <div class="card mb-3 border-0">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-body p-1">
                                <h1 class="mb-0 h2 pe-4 pb-4">{{ producto.titulo }}</h1>
                                <div class="bg-light"><img class="img-fluid mx-auto d-block" width="200px"
                                        alt="Responsive image" src="{{ producto.imagen.url }}"> </div>
                            </div>

                        </div>
                    </div>
                </div>



            </div>

        </div>
    </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productoqty: $('#select option:selected').text(),
                productoid: $('#add-button').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}