basket/urls.py
from django.urls import path
from . import views 

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls', namespace='tienda')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.productos_all, name='productos_all'),
    path('libro/<slug:slug>/', views.producto_detail, name='producto_detail'),
    path('search/<slug:categoria_slug>/', views.category_list, name='category_list'),
    path('acerca', views.acerca, name='acerca'),
    





    
]

basket/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(activo=True)


class Categoria(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)


    class meta:
        verbose_name_plural = 'Categorias'

    def get_absolute_url(self):
        return reverse('tienda:category_list', args=[self.slug])


    def __str__(self):
        return self.name



class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='producto', on_delete=models.CASCADE)
    creado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='creador_producto' )
    titulo = models.CharField(max_length=255)
    autor = models.CharField(max_length=255, default='admin')
    descripcion = models.TextField(blank=True)
    imagen = models.ImageField(upload_to='images/', default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    stock = models.BooleanField(default=True)
    precio = models.DecimalField(max_digits=4, decimal_places=2)
    activo = models.BooleanField(default=True)
    creado = models.DateField(auto_now_add=True)
    actualizado = models.DateField(auto_now=True)
    productos = ProductManager()
    objects = models.Manager()

    

    

    class Meta:
        verbose_name_plural = 'Productos'
        ordering = ('-creado',)

    def get_absolute_url(self):
        return reverse('tienda:producto_detail', args=[self.slug] )
        


    def __str__(self):
        return self.titulo


        

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from tienda.models import Producto
from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'tienda/basket/summary.html', {'basket': basket})



def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        producto_id =int(request.POST.get('productoid'))
        producto_qty =int(request.POST.get('productoqty'))
        producto = get_object_or_404(Producto, id=producto_id)
        basket.add(producto=producto, qty=producto_qty)    
        
          
        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response

def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        producto_id =int(request.POST.get('productoid'))
        basket.delete(producto=producto_id)

        basketqty = basket.__len__()
        baskettotal = basket.precio_total()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response



def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        producto_id = int(request.POST.get('productoid'))
        producto_qty = int(request.POST.get('productoqty'))
        basket.update(producto=producto_id, qty=producto_qty)

        basketqty = basket.__len__()
        baskettotal = basket.precio_total()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

tienda/views.py
from .models import Categoria, Producto
from django.shortcuts import get_object_or_404, render
# Create your views here.


def productos_all(request):
    productos= Producto.objects.filter(activo=True)
    return render(request, 'tienda/home.html', {'productos': productos})


def producto_detail(request, slug):
    producto = get_object_or_404(Producto, slug=slug, stock=True)
    return render(request, 'tienda/productos/single.html', {'producto' : producto})

def category_list(request, categoria_slug=None):
    categoria = get_object_or_404(Categoria, slug=categoria_slug)
    productos = Producto.objects.filter(categoria=categoria)
    return render(request, 'tienda/productos/categoria.html', {'categoria': categoria, 'productos': productos})

def acerca(request):
    return render(request, 'tienda/acerca.html')

templates/tienda/basket/summary.html
  
{% extends "../base.html" %} {% load static %} {% block title %}Resumen{%endblock %} 

{% block content %}


<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2">Tu carrito</h1>
    </div>
    <div class="col-12">
      <p>Controla los <b>articulos</b> en tu carrito</p>
    </div>
    <hr />
  </div>
  <div class="container" style="max-width: 1000px">
    
    <div class="row g-3">
      <div class="col-12 bg-light p-3 d-flex justify-content-between">
        <div class="d-flex d-flex-inline">
          <div class="pe-3">Orden</div>
          <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
          </svg>
          </a>
          </ul>
          </div>
        </div>
        <div class="text-end">
          <div class="pt-2">Total a pagar: <span class="fw-bold h5">$</span><span id="total" class="fw-bold h5">{{basket.precio_total}}</span></div>
          
        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
        <div class="d-grid gap-2 ">
          <a role="button" href="" class="btn btn-success fw-bold" type="button">Pagar</a>
          <button class="btn btn-light" type="button">Guardarlo en favoritos</button>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 p-0">

        {% for item in basket %} 
        {% with producto=item.producto %}

        <div class="card mb-3 border-0 producto-item" data-index="{{producto.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid mx-auto d-block" alt="Responsive image"
                  src="{{ producto.imagen.url }}" />
            </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.producto.get_absolute_url}}">
                  <p class="card-text pb-3">{{producto.titulo}}</p>
                </a>
                    <label for="select">Cantidad</label>
                    <select id="select{{producto.id}}" style="width:50px;height:31px;">
                      <option value="" selected disabled hidden>{{item.qty}}</option>
                      <option value="">1</option>
                      <option value="">2</option>
                      <option value="">3</option>
                      <option value="">4</option>
                    </select>
                <a type="button" id="update-button" data-index="{{producto.id}}" class="update-button text-decoration-none small ps-3">Actualizar</a>
                <a type="button" id="delete-button" data-index="{{producto.id}}" class="delete-button text-decoration-none small">Borrar</a>
              </div>
            </div>
          </div>
        </div>
        {% endwith %} 
        {% endfor %}
      </div>
    </div>
    
  </div>
</main>

<script>

  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productoid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.producto-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty


      },
      error: function (xhr, errmsg, err) {}
    });
  })
 
 
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_update" %}',
      data: {
        productoid: $(this).data('index'),
        productoqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}