account/urls.py
  
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (UserLoginForm)


app_name = 'account'

urlpatterns = [ 
    
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),


    


    
    
    ]

basket/urls.py
from django.urls import path
from . import views 

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls', namespace='tienda')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.productos_all, name='productos_all'),
    path('libro/<slug:slug>/', views.producto_detail, name='producto_detail'),
    path('search/<slug:categoria_slug>/', views.category_list, name='category_list'),
    path('acerca', views.acerca, name='acerca'),
    





    
]

tienda/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(activo=True)


class Categoria(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)


    class meta:
        verbose_name_plural = 'Categorias'

    def get_absolute_url(self):
        return reverse('tienda:category_list', args=[self.slug])


    def __str__(self):
        return self.name



class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='producto', on_delete=models.CASCADE)
    creado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='creador_producto' )
    titulo = models.CharField(max_length=255)
    autor = models.CharField(max_length=255, default='admin')
    descripcion = models.TextField(blank=True)
    imagen = models.ImageField(upload_to='images/', default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    stock = models.BooleanField(default=True)
    precio = models.DecimalField(max_digits=4, decimal_places=2)
    activo = models.BooleanField(default=True)
    creado = models.DateField(auto_now_add=True)
    actualizado = models.DateField(auto_now=True)
    productos = ProductManager()
    objects = models.Manager()

    

    

    class Meta:
        verbose_name_plural = 'Productos'
        ordering = ('-creado',)

    def get_absolute_url(self):
        return reverse('tienda:producto_detail', args=[self.slug] )
        


    def __str__(self):
        return self.titulo


        

tienda/views.py
from .models import Categoria, Producto
from django.shortcuts import get_object_or_404, render
# Create your views here.


def productos_all(request):
    productos= Producto.objects.filter(activo=True)
    return render(request, 'tienda/home.html', {'productos': productos})


def producto_detail(request, slug):
    producto = get_object_or_404(Producto, slug=slug, stock=True)
    return render(request, 'tienda/productos/single.html', {'producto' : producto})

def category_list(request, categoria_slug=None):
    categoria = get_object_or_404(Categoria, slug=categoria_slug)
    productos = Producto.objects.filter(categoria=categoria)
    return render(request, 'tienda/productos/categoria.html', {'categoria': categoria, 'productos': productos})

def acerca(request):
    return render(request, 'tienda/acerca.html')

templates/tienda/acerca.html
{% extends "./base.html" %}
{% load static %}

{% block title %}JAGUARETEBOOKS{% endblock %}

{%block content%}
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Nuestra historia</h1>
       
        <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
         pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
 ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat 
 cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
        
      </div>
    </div>
  </section>


 

</main>

{% endblock %}

templates/tienda/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}JAGUARETE KAA{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/basket.css' %}">
    <link rel="icon" href="/media/logo.jpg">

</head>

<body>
    <header class="pb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand d-flex-inline" href="/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor"
                            class="bi bi-asterisk" viewBox="0 0 16 16">
                            <path
                                d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
                        </svg>
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Catalogo
                                <i class="ps-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                                    </svg></i>         
                            </a>
                            <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "tienda:productos_all" %}">Todos</a></li>
                                {% for c in categorias  %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                      
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Tienda</span>
                    </button>
             {% if user.is_authenticated %}
                    <a type="button" role="button" href="{% url "account:logout" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Logout</span>
                    </a>
                    {% else %}
                    <a type="button" role="button" href="{% url 'account:login' %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Login</span>
                    </a>
                    {% endif %}


                    <a type="button" role="button" href="{% url "account:dashboard" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Cuenta</span>
                    </a>

                    <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">

                        {% with total_qty=basket|length %}
                        <div id="basket-qty" class="basket-qty">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-cart3" viewBox="0 0 16 16">
                                <path
                                    d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Carrito</span>
                    </a>
                </div>
                <div class="d-md-none d-lg-none d-xl-none">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li><a class="dropdown-item" href="{% url "tienda:productos_all" %}">All</a></li>
                            {% for c in categorias %}
                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <form class="d-flex w-100 d-md-none">
                    <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                        aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <div id="content">{% block content %} {% endblock %}</div>

    <footer class="container py-5 footer">
        <hr>
        <div class="row pt-4">
            <div class="col-12 col-md">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-asterisk" viewBox="0 0 16 16">
                    <path
                        d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
                </svg>
                <small class="d-block mb-3 text-muted">&copy; 2021-2021</small>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Contacto</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">JAGUARETE KAA S.A</a></li>
                    <li><a class="link-secondary text-decoration-none" href="/acerca">Acerca de nosotros</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Gonzalo Daniel Rodriguez Bruno</a></li>
           </div>
        </div>
    </footer>
</body>

</html>

templates/tienda/home.html
{% extends "./base.html" %}
{% load static %}

{% block title %}JAGUARETEBOOKS{% endblock %}

{%block content%}
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-3">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Bienvenidos a Jaguarete KAA S.A</h1>
        <p class="lead text-muted">Tu mejor opcion en la compra de libros </p>
        <p>
        {% if user.is_authenticated %}
                  <a href="{% url "account:dashboard" %}" class="btn btn-primary my-2">Crear cuenta</a>

          
                    {% else %}

      
        
          <a href="{% url "account:register" %}" class="btn btn-primary my-2">Crear cuenta</a>
        </p>
                            {% endif %}

      </div>
    </div>
  </section>


 <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">Nuestros libros</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for productos in productos %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Imagen Responsiva" src="{{ productos.imagen.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ productos.get_absolute_url }}">{{ productos.titulo }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Recien llegados</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}